yamllint

diff --git a/.github/workflows/linux.yaml b/.github/workflows/linux.yaml
--- a/.github/workflows/linux.yaml
+++ b/.github/workflows/linux.yaml
@@ -1,3 +1,4 @@
+---
 name: Linux
 on:
   push:
@@ -36,12 +37,17 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt-get -qq update
-          sudo apt-get -y install gcc-multilib build-essential flex zlib1g-dev gnat gdc expect dejagnu libc-dev libc-devtools texlive findutils binutils autogen gettext autopoint libasprintf-dev libgettextpo-dev mailutils mailutils-mh procmail emacs exim4-base msmtp bsd-mailx
+          sudo apt-get -y install gcc-multilib build-essential flex zlib1g-dev \
+            gnat gdc expect dejagnu libc-dev libc-devtools texlive findutils \
+            binutils autogen gettext autopoint libasprintf-dev \
+            libgettextpo-dev mailutils mailutils-mh procmail emacs exim4-base \
+            msmtp bsd-mailx
 
       - name: Install dependencies for aarch64
         if: success() && contains(matrix.target, 'aarch64')
         run: |
-          sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
+          sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
+            binutils-aarch64-linux-gnu
 
       - name: Stamp
         if: success()
@@ -107,7 +113,9 @@ jobs:
         if: success()
         run: |
           cd ../build
-          if test -x "$(which nproc)"; then echo "nproc says that we can use $(nproc) build jobs"; else echo "error: missing nproc!" >&2 && exit 1; fi
+          if test -x "$(which nproc)"; then \
+            echo "nproc says that we can use $(nproc) build jobs"; \
+          else echo "error: missing nproc!" >&2 && exit 1; fi
           time (make -j"$(nproc)" | tee build.log)
           if test -e build.log; then stat build.log && wc -l build.log; fi
 
@@ -115,7 +123,8 @@ jobs:
         if: failure()
         run: |
           if test -r build.log; then grep -i "error:" build.log; \
-          elif test -r ../build/build.log; then grep -i "error:" ../build/build.log; \
+          elif test -r ../build/build.log; then \
+            grep -i "error:" ../build/build.log; \
           elif test -e ../build/Makefile; then \
             sudo apt-get -y install remake; \
             cd ../build; \
@@ -150,26 +159,33 @@ jobs:
         if: success()
         run: |
           if test -x /usr/bin/x86_64-linux-gnu-gcc; then \
-            /usr/bin/x86_64-linux-gnu-gcc --version && /usr/bin/x86_64-linux-gnu-gcc -v; \
+            /usr/bin/x86_64-linux-gnu-gcc --version; \
+            /usr/bin/x86_64-linux-gnu-gcc -v; \
           elif test -x ../build/gcc/xgcc; then \
             ../build/gcc/xgcc --version && sync && ../build/gcc/xgcc -v; \
           fi
           cd ../build
           if test -e build.log; then make warning.log; fi
           time (make -k -j"$(nproc)" check RUNTESTFLAGS="compile.exp dg-torture.exp execute.exp old-deja.exp" | tee testsuite_output.log)
-          if test -e warning.log; then make mail-report-with-warnings.log; else make mail-report.log; fi
+          if test -e warning.log; then \
+            make mail-report-with-warnings.log; \
+          else make mail-report.log; fi
           if test -x "$(which Mail)"; then \
             if test -x mail-report-with-warnings.log; then \
               echo "attempting to send mail-report-with-warnings.log"; \
               ./mail-report-with-warnings.log; \
-              stat mail-report-with-warnings.log && wc -l mail-report-with-warnings.log; \
+              stat mail-report-with-warnings.log; \
+              wc -l mail-report-with-warnings.log; \
+              du mail-report-with-warnings.log; \
             elif test -x mail-report.log; then \
               echo "attempting to send mail-report.log"; \
               ./mail-report.log; \
-              stat mail-report.log && wc -l mail-report.log && du mail-report.log; \
+              stat mail-report.log && wc -l mail-report.log; \
+              du mail-report.log; \
             elif test -e testsuite_output.log; then \
               echo "TODO: figure out a way to send testsuite_output.log"; \
-              stat testsuite_output.log && wc -l testsuite_output.log && du testsuite_output.log; \
+              stat testsuite_output.log && wc -l testsuite_output.log; \
+              du testsuite_output.log; \
             else \
               echo "Nothing to send."; \
             fi; \
