Update linux-go.yaml
1 more of these and then I give up

diff --git a/.github/workflows/linux-go.yaml b/.github/workflows/linux-go.yaml
--- a/.github/workflows/linux-go.yaml
+++ b/.github/workflows/linux-go.yaml
@@ -120,10 +120,17 @@ jobs:
           time (make -S -j"$(nproc)" | tee build.log) || (echo "error: failure!" >&2 && exit 1)
           if test -r build.log && test -s build.log; then \
             sync && stat build.log && wc -l build.log && du build.log; \
-            test -z "$(grep "error:" build.log)" || (echo "error: error found in build.log!" >&2 && exit 1)
+            if test -z "$(grep "error:" build.log)"; then \
+              sync && echo "no errors found in build.log; ok"; \
+            else \
+              echo "error: error found in build.log!" >&2 && exit 1; \
+            fi; \
           elif test -e build.log; then \
+            echo "warning: build.log present, but there might be something wrong with it..." >&2; \
             stat build.log || wc -l build.log || du build.log; \
-          else (ls ./*.log >&2 || (echo "error: no logfiles found!" && exit 1)); fi
+          else \
+            ls ./*.log >&2 || (echo "error: no logfiles found!" >&2 && exit 1); \
+          fi
           sync && echo "Done with main build step." && sync
 
       - name: Debug failure
